services:
  db:
    image: postgres:15  # Use a compatible version
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apollo_photography_development
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent storage for database

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: apollo_photography_development

volumes:
  pgdata:
